kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world

- name: ansible-test
  image: plugin/ansible
  settings:
    become: true
    playbook: ansible-material/playbook.yml
    inventory: ansible-material/inventory
    ssh_extra_args: "-o StrictHostKeyChecking=no"
//    requirements: requirements.txt
    galaxy: ansible-material/requirements.yml
    syntax_check: true
